"""Initial Flask-AAS schema

Revision ID: 29cf3dc887a0
Revises: 
Create Date: 2026-08-18 15:06:04.592004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cf3dc887a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('referer', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('failure_reason', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logins_failure_reason'), ['failure_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logins_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logins_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logins_username'), ['username'], unique=False)

    op.create_table('country',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('iso_code_2', sa.String(length=2), nullable=False),
    sa.Column('iso_code_3', sa.String(length=3), nullable=False),
    sa.Column('address_format', sa.Text(), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_country_iso_code_2'), ['iso_code_2'], unique=True)
        batch_op.create_index(batch_op.f('ix_country_iso_code_3'), ['iso_code_3'], unique=True)

    op.create_table('onlineusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=60), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onlineusers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onlineusers_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_onlineusers_last_active'), ['last_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_onlineusers_user'), ['user'], unique=False)

    op.create_table('plugin_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(length=100), nullable=False),
    sa.Column('import_path', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('configured', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_path')
    )
    with op.batch_alter_table('plugin_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_registrations_plugin_id'), ['plugin_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('auth_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('alt_phone', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zone_code', sa.String(length=16), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('reg_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('activated', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('otp_secret', sa.String(length=32), nullable=True),
    sa.Column('pending_otp_secret', sa.String(length=32), nullable=True),
    sa.Column('pending_otp_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_totp_counter', sa.BigInteger(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=255), server_default='', nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_activities_timestamp'), ['timestamp'], unique=False)

    op.create_table('env_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=50), nullable=False),
    sa.Column('site_url', sa.String(length=100), nullable=True),
    sa.Column('site_lang', sa.String(length=5), nullable=False),
    sa.Column('site_timezone', sa.String(length=60), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('keywords', sa.Text(), server_default='', nullable=False),
    sa.Column('admin_name', sa.String(length=50), nullable=True),
    sa.Column('admin_email', sa.String(length=100), nullable=True),
    sa.Column('site_mode', sa.SmallInteger(), nullable=False),
    sa.Column('default_role_id', sa.Integer(), nullable=True),
    sa.Column('users_per_page', sa.SmallInteger(), nullable=False),
    sa.Column('users_stored_path', sa.String(length=255), nullable=False),
    sa.Column('max_failed_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('lockout_duration_seconds', sa.Integer(), server_default=sa.text('(900)'), nullable=False),
    sa.Column('password_policy_enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), server_default=sa.text('(20)'), nullable=False),
    sa.Column('password_require_uppercase', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('password_require_lowercase', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('password_require_number', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('password_require_special', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('password_check_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('password_check_provider', sa.String(length=50), server_default='local', nullable=False),
    sa.Column('use_mfa', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('use_verify_email', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('use_user_approval', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('use_user_location', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('use_captcha', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('contact_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('spam_check_enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('spam_check_provider', sa.String(length=50), server_default='local', nullable=False),
    sa.Column('maint_mode', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('visitor_tracking', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('use_fancy_urls', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('enable_plugins', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('enable_delete_old_users', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('users_delete_after_days', sa.SmallInteger(), nullable=False),
    sa.Column('email_after_days', sa.SmallInteger(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('page_home_html', sa.Text(), nullable=True),
    sa.Column('page_about_html', sa.Text(), nullable=True),
    sa.Column('page_privacy_html', sa.Text(), nullable=True),
    sa.Column('page_terms_html', sa.Text(), nullable=True),
    sa.Column('use_smtp', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_security', sa.String(length=10), server_default='starttls', nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_pass', sa.Text(), nullable=True),
    sa.Column('smtp_default_sender', sa.String(length=255), nullable=True),
    sa.Column('enable_analytics', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('allow_custom_themes', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('enable_logging', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('log_level', sa.String(length=10), server_default='INFO', nullable=False),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], name='fk_env_settings_default_role_id_roles'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_profiles_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code_hash', name='uq_mfa_recovery_codes_user_hash')
    )
    with op.batch_alter_table('mfa_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_recovery_codes_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfa_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('remembered', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_sessions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('parent_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['parent_zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('zone_id')
    )
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_zone_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_parent_zone_id'), ['parent_zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_parent_zone_id'))
        batch_op.drop_index(batch_op.f('ix_zone_country_id'))
        batch_op.drop_index(batch_op.f('ix_zone_code'))
        batch_op.drop_index(batch_op.f('ix_zone_active'))

    op.drop_table('zone')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_consumed_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('mfa_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_recovery_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_mfa_recovery_codes_consumed_at'))

    op.drop_table('mfa_recovery_codes')
    op.drop_table('env_settings')
    with op.batch_alter_table('audit_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_activities_timestamp'))

    op.drop_table('audit_activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('plugin_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_registrations_plugin_id'))

    op.drop_table('plugin_registrations')
    with op.batch_alter_table('onlineusers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onlineusers_user'))
        batch_op.drop_index(batch_op.f('ix_onlineusers_last_active'))
        batch_op.drop_index(batch_op.f('ix_onlineusers_ip_address'))

    op.drop_table('onlineusers')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_iso_code_3'))
        batch_op.drop_index(batch_op.f('ix_country_iso_code_2'))
        batch_op.drop_index(batch_op.f('ix_country_active'))

    op.drop_table('country')
    with op.batch_alter_table('audit_logins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logins_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logins_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logins_ip_address'))
        batch_op.drop_index(batch_op.f('ix_audit_logins_failure_reason'))

    op.drop_table('audit_logins')
    # ### end Alembic commands ###
